/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lab */

#ifndef _Included_lab
#define _Included_lab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lab
 * Method:    SSE
 * Signature: ([II[I)V
 */
JNIEXPORT void JNICALL Java_lab_SSE
  (JNIEnv *, jclass, jintArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
